# Generated by Django 4.1.5 on 2024-07-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_date', models.DateField()),
                ('slot', models.CharField(choices=[('MORNING', 'Morning (10:00 AM to 01:00 PM)'), ('AFTERNOON', 'Afternoon (02:00 PM to 06:00 PM)')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('appointment_fees', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
