# Generated by Django 4.2.4 on 2024-07-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient_fees",
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
